---
title: Next Generation Sequencing Facilitates Quantitative Analysis of A549 Control
  and A549 infected with Zika virus Transcriptomes
author: "Jingjing Qi"
date: "March 22, 2005"
output:
  ioslides_presentation: default
  beamer_presentation:
    fig_height: 6
    fig_width: 7
    fonttheme: structureitalicserif
    latex_engine: xelatex
    slide_level: 2
    theme: CambridgeUS
    toc: yes
---

# Introduction   

## BackGround   

### Zika Virus  
    - Arthropod-borne virus(transmited by Arthropod)    
    - Genus Flavivirus(+ sense ssRNA,  10–11kb in length)    
### Previous study   
    - in-vitro study had shown that ZIKV replication persists in human 
    fetal neural progenitors (hNPs) for at least 28 days    

## Paper of Source

### BackGround    
    -  Human Fetal Astrocytes Infected with Zika Virus Exhibit Delayed 
       Apoptosis and Resistance to Interferon: Implications for 
       Persistence. *Daniel Limonta, Juan Jovel, Anil Kumar, et al.* 
       Viruses 2018, 10, 646    
        
    - hNPs can be differentiated into astrocytes. 
    - Human fetal astrocytes(HFAs) is the most abundant cell type in 
      the central nervous system.    
    
### Speculation   
    - HFAs possibly functioned as Viral reservoirs that may contribute 
      to the establishment of chronic brain infection and 
      neurodevelopmental abnormalities.   
    
## Evidence:  
    - HFAs is permissive to ZIKV infection.     
    - Low level of apoptosis in HFAs; sustained cytokine antiviral response.    
    - qrtPCR ZIKV genomes suggest that adaptive mutations were not required.     
    - RNAseq analyses suggests that ZIKV alters host gene expression 
      in a manner that could affect developmental processes.         

# Methods    

## Sample       
    - HFAs were obtained from 15 to 19-week aborted fetuses.     
    - Positive Control: continuous human cell lines A549 cells overexpress AXL.   
    - Condition: infected with Zika virus and un-infected    
    - Replication: 3    

## Bioinformatic   
    - RNA isolation using RNeasy mini kit (QIAGEN, Valencia, CA, USA). 
    - RNAseq libraries prep: TruSeq RNA Sample Prep V2 Kit. 
    - Sequencer: Illumina Hiseq4000.  
    
    - QC: fastqc-all passed without trimming    
    - Genorme: Ensemble GRCh38.99
    - Alignment: Star default twopassMode    
    - Post QC: all passed    
    - DEseq     
    - DEXseq  

# Result    

##

## Alignment    

## DEseq    

## GO Analysis  

## DEXseq    


# Disscussion    
##  
    -
##
    -    

---
